### ISSUE TITLE
Application only error responses are garbled

### ISSUE THREAD

**Issue by weingart** [ChimeraCoder/anaconda#153] opened 2016-06-04 23:07 UTC
Using only a consumer secret/key, in order to use application auth only, I attempted to get the home timeline, which rightly should be denied.  However, printing the error results in:

```
2016/06/04 15:46:54 Get https://api.twitter.com/1.1/statuses/home_timeline.json?contributor_details=true&count=20&exclude_replies=true&include_entities=true returned status 403, x?
                    ?1
?0
  ????ұ?i?Bm ?8?n???X???????)?q?ǀM?????B?jM_ ?)!?&>9
                                                    .?ZfOi??????     9
```

Chances are, the body is compressed (Content-Encoding likely == 'gzip').  A possible solution may be (if this is the case): https://www.socketloop.com/tutorials/golang-read-gzipped-http-response

Also, ignoring the json decode here: https://github.com/ChimeraCoder/anaconda/blob/afffdbac178c0e78746ea42d7c1af963cb7ef28e/errors.go#L47 is likely not a good thing.  :)

**Comment by weingart** [comment] 2016-06-04 23:16
Yup... grabbing the error and printing out the headers gives:
```
Content-Encoding":[]string{"deflate"}
```

**Comment by weingart** [comment] 2016-06-04 23:24
Possible solution: https://play.golang.org/p/Ldasu_mpxl

**Comment by Gurpartap** [comment] 2017-10-22 05:17
@weingart Did you deploy the fix? I'm currently ignoring body `if utf8.ValidString(apierr.Body) {...}` but want to parse the response into a proper string.

**Comment by Gurpartap** [comment] 2017-10-22 05:21
Looks like this was fixed recently: https://github.com/ChimeraCoder/anaconda/pull/179

**Comment by muesli** [comment] 2017-11-18 02:15
I also think this should be fixed now. Please let us know if you can still reproduce this issue with anaconda's master. Thanks for your report!

**Closed by muesli** 2017-11-18 02:15 UTC
