### ISSUE TITLE
GetFriendsListAll return only 200 friends

### ISSUE THREAD

**Issue by melihmucuk** [ChimeraCoder/anaconda#110] opened 2015-11-13 11:57 UTC
I tried get all friends of user but it returns only 200 of them. How can I get all of them ?

<pre><code>api := getNewAPI(token, tokenSecret)
v := url.Values{}
v.Set("count", "200")
v.Set("skip_status", "true")
friends := <-api.GetFriendsListAll(v)</code></pre>

**Comment by Francesco149** [comment] 2015-11-16 17:23
Well, you are setting count to 200, so it's only getting 200 friends as you requested.

See count and cursor parameters here
https://dev.twitter.com/rest/reference/get/friends/ids

GetFriendsListAll should already set cursor correctly and re-call the api until the full list has been retrieved, so all you should need to do is:

```go

api := getNewAPI(token, tokenSecret)
v := url.Values{}
v.Set("skip_status", "true")
friends := <-api.GetFriendsListAll(v)

```

**Comment by melihmucuk** [comment] 2015-11-16 17:57
Did you test it ? If you don't set the count, it returns just 20 (default) results.

**Comment by Francesco149** [comment] 2015-11-16 18:21
Nah, I'm just speculating.
Let's see, the function description says
```go

// Like GetFriendsList, but returns a channel instead of a cursor and pre-fetches the remaining results
// This channel is closed once all values have been fetched

```

this likely means that you have to keep fetching data from the channel until it is closed, so maybe something like this?
```go

api := getNewAPI(token, tokenSecret)
v := url.Values{}
v.Set("skip_status", "true")
chFriends := api.GetFriendsListAll(v)

var allFriends []anaconda.User
for {
    friends, more := <-chFriends
    allFriends = append(allFriends, friends)
    if !more {
        break
    }
}
``

**Comment by melihmucuk** [comment] 2015-11-17 12:38
Get friends request has request limit on twitter side. How to handle rate limiting ? If I set the count=200 for next 15 request, I can get only 3000 friends. What if the user has more than 3000 friends ? Anyway thanks for your attention. @Francesco149

**Comment by Francesco149** [comment] 2015-11-17 12:57
hmm what's the specific use case for this? because most of the time you'll want the user to just browse the friends list page by page and never retrieve all friends at once. anaconda has rate limiting (api.SetDelay) to set a delay between each request.

Additionally, the other api (which only gets friend id's) I linked earlier can retrieve up to 5000 friends in one request https://dev.twitter.com/rest/reference/get/friends/ids and is used by GetFriendsIds

```go

var friendIds []int64
v = url.Values{}
v.Set("count", "5000")
v.Set("screen_name", "user screen name")
next_cursor := "-1"
for next_cursor != "0" {
    v.Set("cursor", next_cursor)
    c, err := a.GetFriendsIds(v)
    if err != nil { log.Fatal(err) }
    friendIds = append(friendIds, c.Ids)
    next_cursor = c.Next_cursor_str
}

```

(untested code)
however if you need more than just the user id you will still need to call GetUsersShowById for each id which has a rate limit of 180 or something like that.

**Comment by melihmucuk** [comment] 2015-11-17 13:02
I want to get all friends of the user and insert the db for my apps. I think I should write a background job for this and handle rate limiting on my server side. @Francesco149

**Comment by Francesco149** [comment] 2015-11-17 13:03
well you could always just store the id's which is quicker and can get 5000 id's per request. but yeah, if you want to cache ALL information then you're definitely gonna need a background job

**Comment by muesli** [comment] 2017-11-18 03:05
Closing as this is a (sensible) limitation of Twitter's API and not a bug in anaconda.

**Closed by muesli** 2017-11-18 03:05 UTC
